name: Build LaTeX document

on:
  push: {}

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Retrieve current version
        shell: bash
        run: echo "{version}={$(date +'%Y-%m-%d')}_${{ github.run_number }}" >> $GITHUB_ENV

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          docker_image: ghcr.io/xu-cheng/texlive-full:20230801
          args: '-pdf -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-directory=out -jobname=Michal_Tulowiecki_${{ env.version }}'

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: out/Michal_Tulowiecki_${{ env.version }}.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/Michal_Tulowiecki_${{ env.version }}.pdf
          tag_name: ${{ github.run_number }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
